
import Footer from './Component/Footer'
import Header from './Component/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import 'keen-slider/keen-slider.min.css'
import GlobalState from '@/context'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cursurvice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <GlobalState>
      <Header></Header>
       <main> {children}</main>
        </GlobalState>
       </body>
      
      <Footer></Footer>
    </html>
  )
}
